In [12]:
import pandas as pd
import numpy as np
import warnings
import random
import math


warnings.filterwarnings('ignore')

In [21]:
df_placar2 = pd.read_csv("vlr_placar2.csv")
df_stats2 = pd.read_csv("vlr_stats2.csv")
df_merged = pd.read_csv("merged_status_placar.csv")
df_matchups = pd.read_csv("matchups_score.csv")


df_geral = pd.read_csv("df_jogador_geral.csv")
df_jog_map = pd.read_csv("jogador_por_mapas.csv")
df_indv = pd.read_csv("status_individual.csv")
df_jog_agente = pd.read_csv("df_jog_agente.csv")

# Visualização dos DF's

In [13]:
df_indv.head(3)

,Mapa,Jogador,Time,Agente,R,ACS,K,D,A,+/-,...,FK,FD,+/-_FK_FD,Vencedor,Adversario,Score_Time,Score_Adv,Mapas_Time,Mapas_Adv,target
0,Haven,Darker,LOUD,Viper,1.12,256,18,16,6,2,...,2,1,1,C9,C9,7.0,13.0,0.0,2.0,0
1,Haven,cauanzin,LOUD,Sova,0.98,209,15,13,3,2,...,0,1,-1,C9,C9,7.0,13.0,0.0,2.0,0
2,Haven,Virtyy,LOUD,Yoru,0.70,178,14,16,4,-2,...,2,3,-1,C9,C9,7.0,13.0,0.0,2.0,0

In [14]:
df_jog_map.head(3)

,Jogador,Time,Mapa,R,ACS,K,D,A,+/-,KAST,ADR,HS%,FK,FD,+/-_FK_FD,Jogos,Wins,WinRate,Impacto
0,infiltrator,KRÜ,Abyss,1.360,293.5,43,30,6,13,87.5,186.0,32.0,5,2,3,2,0,0.0,1.383
1,lukxo,LOUD,Abyss,1.443,279.7,77,44,8,33,75.7,174.7,34.7,12,10,2,3,0,0.0,1.363
2,vora,100T,Abyss,1.385,255.5,33,22,6,11,82.0,163.5,28.5,2,2,0,2,1,0.5,1.304

In [15]:
df_geral.head(3)

,Jogador,Time,K,D,A,+/-,FK,FD,+/-_FK_FD,R,ACS,KAST,ADR,HS%,Score_Time,Score_Adv,Mapas_Time,Mapas_Adv,Impacto
0,Darker,LOUD,262,288,112,-26,34,34,0,0.932,195.5,70.0,123.0,25.0,148,232,4,26,0.593
1,cauanzin,LOUD,1248,1424,512,-176,148,208,-60,0.896,187.7,68.6,124.8,25.1,892,1062,52,110,0.558
2,Virtyy,LOUD,648,694,160,-46,144,182,-38,0.885,195.5,66.2,121.6,24.7,400,532,20,58,0.565

In [22]:
df_jog_agente.head(3)

,Jogador,Time,Agente,R,ACS,K,D,A,+/-,KAST,ADR,HS%,FK,FD,+/-_FK_FD,Jogos,Wins,WinRate,Impacto
0,johnqt,SEN,Astra,1.500,234.0,47,21,14,26,92.0,149.5,32.0,2,0,2,2,1,0.50,0.807
1,s0m,NRG,Astra,1.433,237.7,49,31,31,18,88.0,151.0,23.7,8,1,7,3,2,0.67,0.803
2,Melser,KRÜ,Astra,1.248,216.6,77,63,37,14,77.2,144.4,35.6,13,6,7,5,0,0.00,0.749

# Visualização com filtro

In [28]:
df_indv[df_indv["Jogador"] == "lukxo"].head(5)

,Mapa,Jogador,Time,Agente,R,ACS,K,D,A,+/-,...,FK,FD,+/-_FK_FD,Vencedor,Adversario,Score_Time,Score_Adv,Mapas_Time,Mapas_Adv,target
4,Haven,lukxo,LOUD,Killjoy,0.65,192,13,16,3,-3,...,4,4,0,C9,C9,7.0,13.0,0.0,2.0,0
10,Abyss,lukxo,LOUD,Chamber,1.46,297,27,16,3,11,...,4,2,2,C9,C9,11.0,13.0,0.0,2.0,0
54,Haven,lukxo,LOUD,Killjoy,0.65,192,13,16,3,-3,...,4,4,0,C9,C9,7.0,13.0,0.0,2.0,0
60,Abyss,lukxo,LOUD,Chamber,1.46,297,27,16,3,11,...,4,2,2,C9,C9,11.0,13.0,0.0,2.0,0
253,Breeze,lukxo,LOUD,Viper,1.04,181,16,16,5,0,...,2,7,-5,LOUD,100T,13.0,11.0,1.0,2.0,1

In [23]:
df_jog_map[df_jog_map["Jogador"] == "lukxo"]

,Jogador,Time,Mapa,R,ACS,K,D,A,+/-,KAST,ADR,HS%,FK,FD,+/-_FK_FD,Jogos,Wins,WinRate,Impacto
1,lukxo,LOUD,Abyss,1.443,279.7,77,44,8,33,75.7,174.7,34.7,12,10,2,3,0,0.00,1.363
94,lukxo,LOUD,Ascent,1.065,221.0,34,27,4,7,59.5,139.5,40.5,9,2,7,2,1,0.50,1.134
187,lukxo,LOUD,Bind,0.903,190.2,57,60,16,-3,67.5,127.2,28.0,7,5,2,4,1,0.25,0.930
266,lukxo,LOUD,Breeze,1.040,181.0,16,16,5,0,75.0,126.0,34.0,2,7,-5,1,1,1.00,0.996
365,lukxo,LOUD,Corrode,0.650,149.0,10,17,4,-7,45.0,104.0,30.0,1,4,-3,1,0,0.00,0.674
442,lukxo,LOUD,Haven,0.979,228.3,104,97,20,7,69.0,149.4,30.7,21,15,6,7,1,0.14,1.139
519,lukxo,LOUD,Icebox,1.153,234.3,59,52,16,7,69.7,154.3,32.3,15,7,8,3,1,0.33,1.204
581,lukxo,LOUD,Lotus,1.413,291.7,77,53,16,24,69.0,188.3,37.0,14,3,11,3,2,0.67,1.355
725,lukxo,LOUD,Pearl,0.895,201.5,29,31,11,-2,57.5,127.5,29.0,1,7,-6,2,0,0.00,0.842
749,lukxo,LOUD,Split,1.220,270.3,68,49,14,19,70.3,171.3,30.3,15,10,5,3,0,0.00,1.266
834,lukxo,LOUD,Sunset,1.250,253.0,34,29,8,5,80.5,171.5,39.0,5,3,2,2,1,0.50,1.297

In [24]:
df_jog_agente[df_jog_agente["Jogador"] == "lukxo"]

,Jogador,Time,Agente,R,ACS,K,D,A,+/-,KAST,ADR,HS%,FK,FD,+/-_FK_FD,Jogos,Wins,WinRate,Impacto
88,lukxo,LOUD,Chamber,1.443,279.7,77,44,8,33,75.7,174.7,34.7,12,10,2,3,0,0.00,0.816
111,lukxo,LOUD,Cypher,1.144,242.2,133,106,24,27,71.4,157.2,35.1,26,9,17,8,3,0.38,0.748
246,lukxo,LOUD,Killjoy,0.928,213.6,74,75,14,-1,61.6,143.4,32.4,13,15,-2,5,0,0.00,0.561
294,lukxo,LOUD,Omen,1.025,222.0,36,36,11,0,73.0,140.5,29.5,11,6,5,2,1,0.50,0.647
440,lukxo,LOUD,Viper,1.055,220.6,179,160,44,19,67.4,145.0,30.9,31,27,4,10,2,0.20,0.709
480,lukxo,LOUD,Vyse,1.180,257.7,66,54,21,12,65.3,166.0,32.0,9,6,3,3,2,0.67,0.754

In [26]:
df_geral[df_geral["Jogador"] == "lukxo"]

,Jogador,Time,K,D,A,+/-,FK,FD,+/-_FK_FD,R,ACS,KAST,ADR,HS%,Score_Time,Score_Adv,Mapas_Time,Mapas_Adv,Impacto
4,lukxo,LOUD,565,475,122,90,102,73,29,1.105,234.5,68.5,152.5,32.6,296,373,24,59,0.725

# Aplicação de ML

-Prever vitória ou derrota

-Descobrir melhores combinações de agente + mapa

-Sistema de recomendação de agentes

-Predição de impacto do agente no resultado

-Simulador de partidas

In [19]:
# Função de Criação de Times
def gerar_time_aleatorio(df, n=5, seed=None):
    time = df.sample(n=n, random_state=seed).reset_index(drop=True)
    return time

time = gerar_time_aleatorio(df_jog_map)
time

,Jogador,Time,Mapa,R,ACS,K,D,A,+/-,KAST,ADR,HS%,FK,FD,+/-_FK_FD,Jogos,Wins,WinRate,Impacto
0,gobera,2G,Icebox,0.375,102.0,12,30,6,-18,58.0,74.5,23.0,1,9,-8,2,0,0.00,0.594
1,Verno,MIBR,Haven,0.979,174.7,118,118,41,0,75.4,118.4,25.0,9,13,-4,9,4,0.44,0.963
2,Shyy,KRÜ,Corrode,0.800,170.5,21,27,5,-6,68.0,115.0,23.0,2,5,-3,2,0,0.00,0.802
3,JonahP,G2,Bind,1.203,214.3,49,37,25,12,77.0,135.7,27.7,2,7,-5,3,3,1.00,1.155
4,Palla,FUR,Icebox,0.920,223.0,9,12,2,-3,69.0,145.0,34.0,2,1,1,1,0,0.00,0.966