In [1]:
import pandas as pd
import numpy as np
import warnings
import random
import math


warnings.filterwarnings('ignore')

In [20]:
df_placar2 = pd.read_csv("vlr_placar2.csv")
df_stats2 = pd.read_csv("vlr_stats2.csv")

df_impc = pd.read_csv("df_impacto_cada_mapa.csv")
df_impc_allmaps = pd.read_csv('df_impacto_allmaps.csv')
df_geral = pd.read_csv('status_individual_geral.csv')

In [3]:
df_impc

,Mapa,Jogador,Time,Agente,R,ACS,K,D,A,+/-,...,FD,+/-_FK_FD,Time1,Score_T1,Time2,Score_T2,target,Impacto_Ofensivo,Impacto_Suporte,Impacto_Geral
0,Haven,Darker,LOUD,Viper,1.12,256.0,18,16,6,2,...,1.0,1.0,LOUD,7,C9,13,0,0.718,0.382,1.100
1,Haven,cauanzin,LOUD,Sova,0.98,209.0,15,13,3,2,...,1.0,-1.0,LOUD,7,C9,13,0,0.638,0.325,0.963
2,Haven,Virtyy,LOUD,Yoru,0.70,178.0,14,16,4,-2,...,3.0,-1.0,LOUD,7,C9,13,0,0.522,0.264,0.786
3,Haven,pANcada,LOUD,Omen,0.67,145.0,11,13,1,-2,...,3.0,-3.0,LOUD,7,C9,13,0,0.462,0.253,0.716
4,Haven,lukxo,LOUD,Killjoy,0.65,192.0,13,16,3,-3,...,4.0,0.0,LOUD,7,C9,13,0,0.534,0.264,0.798
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7785,Fracture,crashies,NRG,Skye,1.24,212.0,19,17,11,2,...,3.0,-3.0,LOUD,13,NRG,11,0,0.688,0.404,1.092
7786,Fracture,s0m,NRG,Brimstone,1.24,240.0,19,18,12,1,...,1.0,1.0,LOUD,13,NRG,11,0,0.698,0.437,1.134
7787,Fracture,Victor,NRG,Killjoy,0.83,168.0,16,17,1,-1,...,2.0,0.0,LOUD,13,NRG,11,0,0.532,0.295,0.827
7788,Fracture,ardiis,NRG,Jett,0.81,210.0,15,19,4,-4,...,3.0,3.0,LOUD,13,NRG,11,0,0.536,0.332,0.868
7789,Fracture,FiNESSE,NRG,Breach,0.65,136.0,10,19,10,-9,...,3.0,-1.0,LOUD,13,NRG,11,0,0.402,0.313,0.715

In [4]:
df_impc_allmaps

,Mapa,Jogador,Time,Agente,R,ACS,K,D,A,+/-,...,FD,+/-_FK_FD,Time1,Score_T1,Time2,Score_T2,target,Impacto_Ofensivo,Impacto_Suporte,Impacto_Geral
0,AllMaps,lukxo,LOUD,Killjoy,1.09,245.0,40,32,6,8,...,6.0,2.0,LOUD,18,C9,26,0,0.780,0.375,1.155
1,AllMaps,Darker,LOUD,Viper,1.03,211.0,33,32,14,1,...,4.0,-1.0,LOUD,18,C9,26,0,0.679,0.385,1.064
2,AllMaps,cauanzin,LOUD,Sova,0.84,188.0,28,33,11,-5,...,6.0,-6.0,LOUD,18,C9,26,0,0.523,0.347,0.870
3,AllMaps,pANcada,LOUD,Omen,0.75,130.0,22,26,10,-4,...,4.0,-3.0,LOUD,18,C9,26,0,0.482,0.342,0.824
4,AllMaps,Virtyy,LOUD,Yoru,0.69,174.0,27,35,7,-8,...,6.0,0.0,LOUD,18,C9,26,0,0.515,0.311,0.826
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3106,AllMaps,s0m,NRG,Omen,1.17,214.0,54,48,21,6,...,5.0,0.0,LOUD,39,NRG,31,0,0.755,0.405,1.160
3107,AllMaps,crashies,NRG,Sova,1.03,185.0,45,51,26,-6,...,5.0,-2.0,LOUD,39,NRG,31,0,0.575,0.364,0.939
3108,AllMaps,ardiis,NRG,Jett,1.00,220.0,49,48,18,1,...,9.0,6.0,LOUD,39,NRG,31,0,0.681,0.407,1.087
3109,AllMaps,Victor,NRG,Kayo,0.85,189.0,48,51,10,-3,...,8.0,-2.0,LOUD,39,NRG,31,0,0.559,0.337,0.896
3110,AllMaps,FiNESSE,NRG,Killjoy,0.67,147.0,30,54,23,-24,...,10.0,-6.0,LOUD,39,NRG,31,0,0.486,0.312,0.798

In [22]:
df_geral.drop_duplicates(inplace=True)
df_geral

,Mapa_Num,Mapa,Jogador,Time,Agente,R,ACS,K,D,A,...,FK,FD,+/-_FK_FD,Time1,Mapas_T1,Score_T1,Time2,Mapas_T2,Score_T2,target
0,0,Haven,Darker,LOUD,Viper,1.12,256.0,18,16,6,...,2.0,1.0,1.0,LOUD,NaN,7,C9,NaN,13,0
2,0,Haven,cauanzin,LOUD,Sova,0.98,209.0,15,13,3,...,0.0,1.0,-1.0,LOUD,NaN,7,C9,NaN,13,0
4,0,Haven,Virtyy,LOUD,Yoru,0.70,178.0,14,16,4,...,2.0,3.0,-1.0,LOUD,NaN,7,C9,NaN,13,0
6,0,Haven,pANcada,LOUD,Omen,0.67,145.0,11,13,1,...,0.0,3.0,-3.0,LOUD,NaN,7,C9,NaN,13,0
8,0,Haven,lukxo,LOUD,Killjoy,0.65,192.0,13,16,3,...,4.0,4.0,0.0,LOUD,NaN,7,C9,NaN,13,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15716,3,Fracture,crashies,NRG,Skye,1.24,212.0,19,17,11,...,0.0,3.0,-3.0,LOUD,NaN,13,NRG,NaN,11,0
15717,3,Fracture,s0m,NRG,Brimstone,1.24,240.0,19,18,12,...,2.0,1.0,1.0,LOUD,NaN,13,NRG,NaN,11,0
15718,3,Fracture,Victor,NRG,Killjoy,0.83,168.0,16,17,1,...,2.0,2.0,0.0,LOUD,NaN,13,NRG,NaN,11,0
15719,3,Fracture,ardiis,NRG,Jett,0.81,210.0,15,19,4,...,6.0,3.0,3.0,LOUD,NaN,13,NRG,NaN,11,0
15720,3,Fracture,FiNESSE,NRG,Breach,0.65,136.0,10,19,10,...,2.0,3.0,-1.0,LOUD,NaN,13,NRG,NaN,11,0

# Perfil do Jogadores

In [7]:
def perfil_historico(nome, df):
    jogador = df[df['Jogador'] == nome].copy()
    
    if jogador.empty:
        print(f"Jogador '{nome}' não encontrado!")
        return
    
    cols_soma  = ['K', 'D', 'A', '+/-', 'FK', 'FD', '+/-_FK_FD']
    cols_media = ['R', 'ACS', 'KAST', 'ADR', 'HS%', 'Impacto_Geral']
    
    soma  = jogador[cols_soma].sum()
    media = jogador[cols_media].mean()
    
    # Por mapa
    por_mapa = jogador.groupby('Mapa')[['Impacto_Geral', 'ACS', 'target']].mean().round(3)
    por_mapa.columns = ['Impacto_med', 'ACS_med', 'Win_Rate']
    por_mapa = por_mapa.sort_values('Impacto_med', ascending=False)
    
    # Por agente
    por_agente = jogador.groupby('Agente')[['Impacto_Geral', 'ACS', 'target']].mean().round(3)
    por_agente.columns = ['Impacto_med', 'ACS_med', 'Win_Rate']
    por_agente = por_agente.sort_values('Impacto_med', ascending=False)

    print(f"=== Perfil Histórico: {nome} ===")
    print(f"Partidas : {len(jogador)}")
    print(f"Win Rate : {jogador['target'].mean():.1%}")
    print(f"Time(s)  : {', '.join(jogador['Time'].unique())}")
    print(f"Mapas    : {jogador['Mapa'].nunique()} diferentes")
    print()
    
    print("--- Médias ---")
    for col, val in media.items():
        print(f"  {col:<10}: {val:.3f}")
    print()
    
    print("--- Totais ---")
    for col, val in soma.items():
        print(f"  {col:<15}: {int(val)}")
    print()
    
    print("--- Por Mapa (ordenado por Impacto) ---")
    for mapa, row in por_mapa.iterrows():
        print(f"  {mapa:<12} | Impacto: {row['Impacto_med']:.3f} | ACS: {row['ACS_med']:.0f} | Win Rate: {row['Win_Rate']:.1%}")
    print()
    
    print("--- Por Agente (ordenado por Impacto) ---")
    for agente, row in por_agente.iterrows():
        print(f"  {agente:<12} | Impacto: {row['Impacto_med']:.3f} | ACS: {row['ACS_med']:.0f} | Win Rate: {row['Win_Rate']:.1%}")

perfil_historico('cortezia', df_impc)

=== Perfil Histórico: cortezia ===
Partidas : 71
Win Rate : 50.7%
Time(s)  : SEN, MIBR
Mapas    : 12 diferentes

--- Médias ---
  R         : 0.963
  ACS       : 194.366
  KAST      : 69.197
  ADR       : 129.817
  HS%       : 34.521
  Impacto_Geral: 0.948

--- Totais ---
  K              : 1106
  D              : 1078
  A              : 323
  +/-            : 28
  FK             : 142
  FD             : 134
  +/-_FK_FD      : 8

--- Por Mapa (ordenado por Impacto) ---
  Bind         | Impacto: 1.033 | ACS: 226 | Win Rate: 33.3%
  Icebox       | Impacto: 1.003 | ACS: 203 | Win Rate: 100.0%
  Haven        | Impacto: 0.990 | ACS: 194 | Win Rate: 62.5%
  Abyss        | Impacto: 0.976 | ACS: 196 | Win Rate: 80.0%
  Breeze       | Impacto: 0.952 | ACS: 192 | Win Rate: 50.0%
  Split        | Impacto: 0.948 | ACS: 197 | Win Rate: 53.8%
  Pearl        | Impacto: 0.948 | ACS: 190 | Win Rate: 83.3%
  Corrode      | Impacto: 0.905 | ACS: 181 | Win Rate: 33.3%
  Lotus        | Impacto: 0.902 | ACS: 182 | Win Rate: 16.7%
  Sunset       | Impacto: 0.886 | ACS: 206 | Win Rate: 50.0%
  Fracture     | Impacto: 0.880 | ACS: 167 | Win Rate: 0.0%
  Ascent       | Impacto: 0.824 | ACS: 177 | Win Rate: 0.0%

--- Por Agente (ordenado por Impacto) ---
  Vyse         | Impacto: 1.002 | ACS: 208 | Win Rate: 33.3%
  Viper        | Impacto: 0.987 | ACS: 209 | Win Rate: 42.1%
  Cypher       | Impacto: 0.943 | ACS: 196 | Win Rate: 44.4%
  Killjoy      | Impacto: 0.917 | ACS: 179 | Win Rate: 81.2%
  Omen         | Impacto: 0.896 | ACS: 180 | Win Rate: 42.9%
  Veto         | Impacto: 0.840 | ACS: 174 | Win Rate: 0.0%
  Astra        | Impacto: 0.786 | ACS: 122 | Win Rate: 100.0%

# Aplicação de ML

-Descobrir melhores combinações de agente + mapa

-Probabilidade de vitoria

-Simulador de partidas

# Chance de vitoria de um jogador

In [24]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report



df_geral = pd.read_csv('status_individual_geral.csv')
df = df_geral.copy()



features = [
    'R',
    'ACS',
    'K',
    'D',
    'A',
    '+/-',
    'KAST',
    'ADR',
    'HS%',
    'FK',
    'FD',
    '+/-_FK_FD',
    'Score_T1',
    'Score_T2'
]

X = df[features]

y = df['target']



X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [25]:
modelo = RandomForestClassifier(
    n_estimators=300,
    max_depth=10,
    random_state=42
)

modelo.fit(X_train, y_train)


y_pred = modelo.predict(X_test)

In [26]:
acc = accuracy_score(y_test, y_pred)

print(f"Acurácia: {acc:.4f}")

print(classification_report(y_test, y_pred))

Acurácia: 0.7866
              precision    recall  f1-score   support

           0       0.78      0.82      0.80      1628
           1       0.80      0.75      0.77      1517

    accuracy                           0.79      3145
   macro avg       0.79      0.79      0.79      3145
weighted avg       0.79      0.79      0.79      3145

In [27]:
modelo.predict_proba(X_test)

array([[0.07475328, 0.92524672],
       [0.81620623, 0.18379377],
       [0.83124564, 0.16875436],
       ...,
       [0.05571768, 0.94428232],
       [0.38877641, 0.61122359],
       [0.28133333, 0.71866667]], shape=(3145, 2))

In [30]:

linha = df_impc[
    (df_impc['Jogador'] == 'lukxo') &
    (df_impc['Mapa'] == 'Corrode') &
    (df_impc['Agente'] == 'Viper')
].iloc[0]


# mesmas features usadas no treino
features = [
    'R',
    'ACS',
    'K',
    'D',
    'A',
    '+/-',
    'KAST',
    'ADR',
    'HS%',
    'FK',
    'FD',
    '+/-_FK_FD',
    'Score_T1',
    'Score_T2'
]


jogador = pd.DataFrame([linha[features]])


prob = modelo.predict_proba(jogador)

chance_vitoria = prob[0][1]

print(f"Jogador: {linha['Jogador']}")
print(f"Mapa: {linha['Mapa']}")
print(f"Agente: {linha['Agente']}")
print(f"Chance de vitória: {chance_vitoria:.2%}")

Jogador: lukxo
Mapa: Corrode
Agente: Viper
Chance de vitória: 7.00%

In [32]:
# selecionar jogador específico do dataframe

linha = df_impc[
    (df_impc['Jogador'] == 'Sato') &
    (df_impc['Mapa'] == 'Corrode') &
    (df_impc['Agente'] == 'Waylay')
].iloc[0]


# mesmas features usadas no treino
features = [
    'R',
    'ACS',
    'K',
    'D',
    'A',
    '+/-',
    'KAST',
    'ADR',
    'HS%',
    'FK',
    'FD',
    '+/-_FK_FD',
    'Score_T1',
    'Score_T2'
]


jogador = pd.DataFrame([linha[features]])


prob = modelo.predict_proba(jogador)

chance_vitoria = prob[0][0]

print(f"Jogador: {linha['Jogador']}")
print(f"Mapa: {linha['Mapa']}")
print(f"Agente: {linha['Agente']}")
print(f"Chance de Derrota: {chance_vitoria:.2%}")

Jogador: Sato
Mapa: Corrode
Agente: Waylay
Chance de Derrota: 47.80%